unstable_features = true
max_width = 160
comment_width = 160
condense_wildcard_suffixes = true
match_block_trailing_comma = true
format_macro_matchers = true
imports_granularity = "Crate"
newline_style = "Unix"
overflow_delimited_expr = true
use_field_init_shorthand = true
wrap_comments = true